spring:
  profiles:
    active:
      - dev

---
server: 
  port: 4003

spring:
  profiles: dev
  application:
    name: spring-cloud-consumer-config-clent

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://localhost:7001/eureka/,http://localhost1:7002/eureka/,http://localhost2:7003/eureka/

---
server: 
  port: 4004

spring:
  profiles: test
  application:
    name: spring-cloud-consumer-config-clent

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://localhost:7001/eureka/,http://localhost1:7002/eureka/,http://localhost2:7003/eureka/
